<?php get_header(); ?>
<?php if(is_singular('post')): while(have_posts()):the_post();$cat=a3ap_primary_cat();$diag=a3ap_is_diagnostic(); ?>
<section class="ap-article-head"><div class="ap-wrap ap-article-head-inner"><div class="ap-breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">الرئيسية</a><?php if($cat): ?> / <a href="<?php echo esc_url(get_category_link($cat)); ?>"><?php echo esc_html($cat->name); ?></a><?php endif; ?></div><?php if($cat): ?><span class="ap-kicker"><?php echo esc_html($cat->name); ?></span><?php endif; ?><h1><?php the_title(); ?></h1><div class="ap-article-meta"><span>آخر تحديث: <?php echo esc_html(get_the_modified_date('j F Y')); ?></span><span><?php echo esc_html(a3ap_read_time()); ?> دقائق قراءة</span><span>فريق أعطال.كوم</span></div></div></section>
<div class="ap-wrap ap-article-layout"><main class="ap-article">
<?php if($diag): ?><div class="ap-diagnostic-summary"><div><small>نوع المحتوى</small><strong>تشخيص عملي</strong></div><div><small>القاعدة</small><strong>اختبر قبل تغيير القطعة</strong></div><div><small>ابدأ بـ</small><strong>الأعراض + الفحص</strong></div></div><?php endif; ?>
<?php if(has_post_thumbnail()): ?><figure class="ap-featured"><?php the_post_thumbnail('full',['loading'=>'eager','fetchpriority'=>'high']); ?></figure><?php endif; ?>
<div class="ap-entry"><?php the_content(); ?></div></main><aside class="ap-sidebar"><div class="ap-side-card"><h3>في هذا المقال</h3><ul class="ap-toc"><?php foreach(a3ap_toc() as $it): ?><li><a href="#<?php echo esc_attr($it['id']); ?>"><?php echo esc_html($it['t']); ?></a></li><?php endforeach; ?></ul></div><div class="ap-side-card ap-side-dark"><span>A3TAL</span><h3>عايز تكمل حسب عربيتك؟</h3><p>اختار الماركة والموديل للوصول لمحتوى أكثر ارتباطًا بسيارتك.</p><a href="<?php echo esc_url(home_url('/choose-your-car/')); ?>">اختر سيارتك</a></div></aside></div>
<?php endwhile; else: ?>
<section class="ap-archive-head"><div class="ap-wrap"><?php if(is_search()): ?><span class="ap-overline">بحث أعطال.كوم</span><h1>نتائج: <?php echo esc_html(get_search_query()); ?></h1><?php elseif(is_archive()): ?><span class="ap-overline">قسم</span><h1><?php the_archive_title(); ?></h1><?php if(get_the_archive_description()): ?><p><?php echo wp_kses_post(get_the_archive_description()); ?></p><?php endif; ?><?php else: ?><h1>أحدث المحتوى</h1><?php endif; ?></div></section><div class="ap-wrap ap-archive-grid"><?php if(have_posts()):while(have_posts()):the_post();a3ap_card();endwhile;else:?><p>لا توجد نتائج مطابقة.</p><?php endif; ?></div>
<?php endif; get_footer(); ?>
