<?php get_header(); while(have_posts()):the_post();$type=get_post_type();$is_showroom=$type==='a3_showroom';$status=a3g_directory_status();$phone=a3cp_field('_a3_phone');$whatsapp=a3cp_field('_a3_whatsapp');$address=a3cp_field('_a3_address');$hours=a3cp_field('_a3_hours');$lat=a3cp_field('_a3_lat');$lng=a3cp_field('_a3_lng');$source=a3cp_field('_a3_official_source_url');$checked=a3cp_field('_a3_source_checked_at'); ?>
<section class="g-directory-single-hero"><div class="g-wrap g-directory-single-grid">
<div><div class="g-breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">الرئيسية</a><span>›</span><a href="<?php echo esc_url(get_post_type_archive_link($type)); ?>"><?php echo $is_showroom?'معارض السيارات':'مراكز الخدمة'; ?></a></div><?php if($status): ?><span class="g-directory-badge g-status-<?php echo esc_attr($status->slug); ?>"><?php echo esc_html($status->name); ?></span><?php endif; ?><h1><?php the_title(); ?></h1><?php if($address): ?><p><?php echo esc_html($address); ?></p><?php endif; ?><div class="g-directory-actions"><?php if($phone): ?><a href="tel:<?php echo esc_attr(preg_replace('/[^0-9+]/','',$phone)); ?>">اتصال</a><?php endif; ?><?php if($whatsapp): ?><a href="https://wa.me/<?php echo esc_attr(preg_replace('/[^0-9]/','',$whatsapp)); ?>" rel="nofollow noopener" target="_blank">واتساب</a><?php endif; ?></div></div>
<div class="g-directory-feature"><?php if(has_post_thumbnail()){the_post_thumbnail('large',['loading'=>'eager']);}else{echo '<span class="g-fallback">A3TAL</span>';} ?></div>
</div></section>
<main class="g-wrap g-directory-single-main">
<div class="g-directory-facts"><?php if($phone): ?><div><small>الهاتف</small><strong><?php echo esc_html($phone); ?></strong></div><?php endif; ?><?php if($hours): ?><div><small>ساعات العمل</small><strong><?php echo nl2br(esc_html($hours)); ?></strong></div><?php endif; ?><?php if($checked): ?><div><small>آخر تحقق</small><strong><?php echo esc_html($checked); ?></strong></div><?php endif; ?></div>
<article class="g-vehicle-panel g-entry"><?php the_content(); ?></article>
<?php if($lat&&$lng): ?><div class="g-vehicle-panel"><div class="g-section-head"><div><span>الموقع</span><h2>الموقع الجغرافي</h2></div></div><a class="g-map-link" href="https://www.google.com/maps?q=<?php echo esc_attr($lat.','.$lng); ?>" rel="nofollow noopener" target="_blank"><?php echo a3g_icon('pin'); ?><span>فتح الموقع على الخريطة</span></a></div><?php endif; ?>
<?php if($source): ?><div class="g-source-note"><span>مرجع التحقق</span><a href="<?php echo esc_url($source); ?>" rel="nofollow noopener" target="_blank">فتح المصدر الرسمي</a></div><?php endif; ?>
</main><?php endwhile;get_footer(); ?>